ci: add pixi update script + dependabot

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -21,3 +21,23 @@ jobs:
             echo "::error::The schema is out of date. Please run 'pixi run schema' and commit the changes."
             exit 1
           fi
+
+  check-requirements-txt:
+    name: Check requirements.txt
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
+      - name: Set up pixi
+        uses: prefix-dev/setup-pixi@fef5c9568ca6c4ff7707bf840ab0692ba3f08293 # v0.9.0
+        with:
+          run-install: false
+      - name: Sync to requirements.txt
+        run: ./.github/scripts/sync-deps.sh
+      - name: Check for changes
+        run: |
+          git diff --exit-code
+          if [ $? -eq 1 ]
+          then
+            echo "::error::The requirements.txt is out of date. Please run './.github/scripts/sync-deps.sh' and commit the changes."
+            exit 1
+          fi
